# -*- coding: utf-8 -*-
"""GetBondPrice_Enumerate_kh3348.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZEq7kx0SD5vqFHW8YX8uS3UrndCUkr8
"""

def getBondPrice_E(face,couponRate,m,yc):
  C=face*couponRate
  pv_coupons=sum(C/(1+yc_t)** (t+1)for t, yc_t in enumerate(yc))
  pv_face=face/(1+yc[-1])**m
  bondPrice=pv_coupons+pv_face
  return (bondPrice)
