# -*- coding: utf-8 -*-
"""getBondPrice_Zip_kh3348.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZEq7kx0SD5vqFHW8YX8uS3UrndCUkr8
"""

def getBondPrice_Z(face,couponRate,times,yc):
  C=face*couponRate
  pv_coupons=sum(C/(1+rate)** t for t, rate in zip(times,yc))
  pv_face=face/(1+yc[-1])** times[-1]
  bondPrice=pv_coupons+pv_face
  return (bondPrice)
