# -*- coding: utf-8 -*-
"""GetBondDuration_kh3348.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZEq7kx0SD5vqFHW8YX8uS3UrndCUkr8
"""

def getBondDuration(y,face,couponRate,m,ppy=1):
  C=(face*couponRate)/ppy
  N=m*ppy
  pvcf_t=sum([(t/ppy)* (C/(1+y/ppy)**t) for t in range(1,N+1)])
  pv_face_t= (N/ppy)* (face/(1+y/ppy)** N)
  weighted_sum = pvcf_t+pv_face_t
  pv_coupons=pvcf_t+pv_face_t
  bondPrice=sum([C/(1+y/ppy)**t for t in range (1,N+1)])+face/(1+y/ppy)**N
  bondDuration=weighted_sum/bondPrice
  return (bondDuration)

# Test values
y=0.03
face=2000000
couponRate=0.04
m=10
ppy=1

getBondDuration(y,face,couponRate,m,ppy)