# -*- coding: utf-8 -*-
"""GetBondPrice_kh3348.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZEq7kx0SD5vqFHW8YX8uS3UrndCUkr8
"""

def getBondPrice(y,face,couponRate,m,ppy=1):
  C=(face*couponRate)/ppy
  N=m*ppy
  pv_coupons=sum([C/(1+y/ppy)**(t) for t in range(1,N+1)])
  pv_face=face/(1+y/ppy)**N
  bondPrice=pv_coupons+pv_face
  return (bondPrice)
