# -*- coding: utf-8 -*-
"""WhoAmI_kh3348.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZEq7kx0SD5vqFHW8YX8uS3UrndCUkr8
"""

#Identify yourself for grading
def WhoAmI():
  return('kh3348')